[project]
name = "gemma3-lo"
version = "0.1.0"
description = "Gemma 3 Impl"
requires-python = ">=3.12"
dependencies = [
    # PyTorch
    "torch",
    "torchvision",

    # Normal Deps
    "numpy>=2.3.4",
    "pillow>=12.0.0",
]
